Fix TestAlarmsCount failure in tempest tests
This will fix following error:
RuntimeError: resource_cleanup for TestAlarmsCount did not call
the super's resource_cleanup.

Change-Id: I700285eb0b0408678b93431bcc3de47e67f28e75
(cherry picked from commit c4db8adfcad7cae9a2cdd538c7070ca6ef3e1401)