Load config only once
Currently when kafka is down on monasca-api startup,
monasca-api enters infinite error loop with
ArgsAlreadyParsedError: arguments already parsed:
  cannot register CLI option

Change-Id: Iabcd830d76ba4225e39843db88ab35555d4ea921
(cherry picked from commit 200c10be96ebd576c9bd992ee51091299eaaf68d)